export const SET_DARKMODE = "SET_DARKMODE";
export const SET_INCOMING_CALL = "SET_INCOMING_CALL";
export const SET_INCOMING_CALL_ACCEPTED = "SET_INCOMING_CALL_ACCEPTED";
export const SET_INCOMING_CALL_REJECT = "SET_INCOMING_CALL_REJECT";
export const SET_OUTGOING_CALL_REJECT = "SET_OUTGOING_CALL_REJECT";
export const SET_OUTGOING_CALL = "SET_OUTGOING_CALL";
export const SET_DISPLAY_EXT_NUM = "SET_DISPLAY_EXT_NUM";
export const SET_DISPLAY_OUTGOING_EXT_NUM = "SET_DISPLAY_OUTGOING_EXT_NUM";
export const SET_VOICE_SECONDS = "SET_VOICE_SECONDS";
export const SET_VOICE_MINUTES = "SET_VOICE_MINUTES";
export const SET_VOICE_HOURS = "SET_VOICE_HOURS";
export const SET_ANSWER_SCREEN = "SET_ANSWER_SCREEN";
export const SET_CHANGE_STATUS = "SET_CHANGE_STATUS";
export const SET_CALL_STATUS = "SET_CALL_STATUS";
export const SET_SHOW_MUTE = "SET_SHOW_MUTE";
export const SET_SHOW_UNMUTE = "SET_SHOW_UNMUTE";
export const SET_SHOW_HOLD = "SET_SHOW_HOLD";
export const SET_SHOW_UNHOLD = "SET_SHOW_UNHOLD";
export const SET_TRANSFERCALL = "SET_CALL_STATUS";
export const SET_SHOW_TRANSFERCALL = "SET_SHOW_TRANSFERCALL";
export const SET_IS_TRANSFER_INITIATED = "SET_IS_TRANSFER_INITIATED";
export const SET_CALL_ACTIVITY = "SET_CALL_ACTIVITY"; 
export const SET_AGENT_INTERACTION = "SET_AGENT_INTERACTION";

export const SET_MAKING_TRANSFERCALL = "SET_MAKING_TRANSFERCALL";
export const SET_CONFERENCE = "SET_CONFERENCE";
export const SET_SHOW_CONFERENCE = "SET_SHOW_CONFERENCE";
export const SET_IS_CONFERENCE_INITIATED = "SET_IS_CONFERENCE_INITIATED";

export const SET_MERGECALL = "SET_MERGECALL";
export const SET_OPEN_SURVEY = "SET_OPEN_SURVEY";
export const SET_MAKECALL_API = "SET_MAKECALL_API";
export const SET_ASTERIK_LOGIN = "SET_ASTERIK_LOGIN"




 
